[package]
name = "ds4linux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.9"
evdev-rs = "0.5"
anyhow = "1"

[dev-dependencies]
hex = "0.4"